### ISSUE TITLE
maxmind data not available anymore

### ISSUE THREAD

**Issue by mathrb** [ratibor78/geostat#12]
Hello,

I'd like to notify that https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz is not accessible anymore.
Therefore the installation fails. I found some link that could contains the right file, but not sure because I don't know what the original file looks like https://www.miyuru.lk/geoiplegacy

Any help much appreciated

**Comment by coristo** [comment]
You can simply log in on www.geolite.maxmind.com and then download files (you can also generate link, but it's paid option ;) )
I've just changed Dockerfile to use local version, but now i've hot problem with config file :f

**Comment by mathrb** [comment]
Hello @pawel-zajac90 
Indeed, I also used a local version after downloading it from maxmind. 
I didn't get any issues with the configuration file.
One thing maybe: be sure in the host to only use the IP like `host = 192.168.0.21` in my case (I'm running everything locally in containers, that's why I can't use localhost)

**Comment by coristo** [comment]
I had problem with db, because i've never used influxdb before ;)
Now it works, i need only to configure grafana to use it.
Did You tried it maybe?

**Comment by mathrb** [comment]
Yes, you can follow the first tutorial of the same author: https://medium.com/@ratibor78/get-system-metrics-for-5-min-with-docker-telegraf-influxdb-and-grafana-97cfd957f0ac

**Comment by ratibor78** [comment]
Hi there, sorry for the late response, I'm working on fixing this issue, there will be an updated version soon with fixes and new features. So I'll close this issue for now,
