### ISSUE TITLE
Does Geostat support InfluxDB2?

### ISSUE THREAD

**Issue by finish06** [ratibor78/geostat#15]

**Comment by ratibor78** [comment]
Hi @finish06, I need to check this, never have had a chase to use it with InfluxDB2.

**Comment by ratibor78** [comment]
Hi, @finish06  I have checked the InfluxDB2 and found that they seriously changed the connection logic so I need to improve this script for supporting the new version. I can start with adding the InfluxDb2 support. Do you think this will be the improvement that will be important and needed in the future?

**Comment by finish06** [comment]
Hello @ratibor78.  I think the importance of this improvement will become more evident over time.  I think InfluxDB2 was just released, so I doubt many are using it yet.  Have a good day!

**Comment by ratibor78** [comment]
Yep, you're right, I'll add the InfluxDB2 support, thanks for the idea. Will close this issue after then. Have a nice day too @finish06 !

**Comment by thyseus** [comment]
Hi, just stepping along to emphasize that i would be really grateful to see a InfluxDB v2 compatible version of this script ! 
Keep up the good work and thanks a lot :)

**Comment by ratibor78** [comment]
I will start this implementation soon, sorry I was a bit out from this theme and then a russian invasion into my home happened, but now I have a plan to return and fix this.

**Comment by ratibor78** [comment]
@thyseus @finish06 Guys, I'll start creating a new version that will support InfluxDB 2 today, will update you ASAP when it'll be done. Have a nice day !

**Comment by ratibor78** [comment]
Hi, BTW are anyone here have experience with FLUX ? And can translate the old influxDB query to modern Flux ? 
@thyseus @finish06 ?

I'm ready to implement the Influxdb2 support but need to test it with Grafana. 

examle = 
SELECT sum("count") AS "metric" FROM "geodata" WHERE ("host" =~ /^$host$/ AND "website"  =~ /^$website$/) AND $timeFilter GROUP BY "geohash"\

**Comment by ratibor78** [comment]
Ok, I have finished with InfluxDB 2 support, now all works fine, so will merge and fix a bit the documentation. 

Will close this issue also. Have a good time and I hope this new geostat program will be useful for you

**Comment by myusufid** [comment]
I have trouble with the Flux query, could you translate the query in Geostat into a Flux query? @ratibor78
