### ISSUE TITLE
Add option to filter per site

### ISSUE THREAD

**Issue by TehloWasTaken** [ratibor78/geostat#17]
Right now it just throws all the logs into one dashboard with sorting per host, but if you're running multiple sites per host, there is no way to track any of that.

Is it an option to add sorting per site so that you can switch between multiple Nginx/Apache sites/virtual hosts?

**Comment by ratibor78** [comment]
Hi, interesting, will check and try to add this possibility. Thanks for the idea.

**Comment by ratibor78** [comment]
Hello @TehloWasTaken, I rewrite this program, and now it can parse more than one log file, so if you want to get GEO metrics from the different virtual hosts or websites from your server you just need to set up Nginx/Apache config with saving access.log for each site in a different file and then add them in settings.ini like website:/path/to/log.log separated with space.

**Comment by ratibor78** [comment]
I'll close the issue now. Have a nice day !
