### ISSUE TITLE
n/a when i hover over a City

### ISSUE THREAD

**Issue by welcometopwn** [ratibor78/geostat#5]
I recently installed your script, removed the auth part because i don't use HTTP auth.

The script starts without an error, and people are marked on the map, but when i hover over the City (dot) it shows n/a. Did i do anything wrong? I doublechecked the config file, the path is correct of the mmdb file.

**Comment by ratibor78** [comment]
Hi @welcometopwn, in fact, this is not an issue, but some kind of limitation from Grafana map plugin and geohash, this script sends a geohash and a country code only, and Grafana WorldMap plugin puts it on the right place. But it doesn't convert geohash to City name. When I wrote this script I try to send a City name instead, but then I found that Grafana plugin can't put it on the right place on the map, so I stopped on geohash.

**Comment by ratibor78** [comment]
In fact, this script can parse and send City name too, after small modification but then you need to find how to show this on the Grafana dashboard.
