### ISSUE TITLE
nginx log pattern

### ISSUE THREAD

**Issue by dontsovcmc** [ratibor78/geostat#7]
Please, add nginx config example. I need nginx log format. Thansk!

**Comment by b4b857f6ee** [comment]
Same issue for me :)

**Comment by vanthoi** [comment]
> Same issue for me :)

You config : https://medium.com/faun/total-nginx-monitoring-with-application-performance-and-a-bit-more-using-8fc6d731051b

**Comment by ratibor78** [comment]
Thanks, @vanthoi for the response, but in that article, I have shown how to enable some extra logging parameters in Nginx with GEO data and so on for the telegraf. 

In fact, you no need any specific Nginx log format for this script, it takes the IPs from the log file and then parses them through the MaxMind database file for searching the real GEO IP.  It must work with any standard Nginx log. 

There will be an updated version soon, with minor bug's fixes, and  I'll update the documentation also.

**Comment by ratibor78** [comment]
I'll close this issue, for now, we can return to it later if you'll have the same problem with the new version also.
